-- Seed / upsert all countries (safe to re-run)
INSERT INTO countries (id, name, continent, flag) VALUES
('AF', 'Afghanistan', 'Asia', 'Afghanistan.svg'),
  ('AL', 'Albania', 'Europe', 'Albania.svg'),
  ('DZ', 'Algeria', 'Africa', 'Algeria.svg'),
  ('AD', 'Andorra', 'Europe', 'Andorra.svg'),
  ('AO', 'Angola', 'Africa', 'Angola.svg'),
  ('AG', 'Antigua and Barbuda', 'North America', 'Antigua and Barbuda.svg'),
  ('AR', 'Argentina', 'South America', 'Argentina.svg'),
  ('AM', 'Armenia', 'Asia', 'Armenia.svg'),
  ('AU', 'Australia', 'Oceania', 'Australia.svg'),
  ('AT', 'Austria', 'Europe', 'Austria.svg'),
  ('AZ', 'Azerbaijan', 'Asia', 'Azerbaijan.svg'),
  ('BS', 'Bahamas', 'North America', 'Bahamas.svg'),
  ('BH', 'Bahrain', 'Asia', 'Bahrain.svg'),
  ('BD', 'Bangladesh', 'Asia', 'Bangladesh.svg'),
  ('BB', 'Barbados', 'North America', 'Barbados.svg'),
  ('BY', 'Belarus', 'Europe', 'Belarus.svg'),
  ('BE', 'Belgium', 'Europe', 'Belgium.svg'),
  ('BZ', 'Belize', 'North America', 'Belize.svg'),
  ('BJ', 'Benin', 'Africa', 'Benin.svg'),
  ('BT', 'Bhutan', 'Asia', 'Bhutan.svg'),
  ('BO', 'Bolivia', 'South America', 'Bolivia.svg'),
  ('BA', 'Bosnia and Herzegovina', 'Europe', 'Bosnia and Herzegovina.svg'),
  ('BW', 'Botswana', 'Africa', 'Botswana.svg'),
  ('BR', 'Brazil', 'South America', 'Brazil.svg'),
  ('BN', 'Brunei', 'Asia', 'Brunei.svg'),
  ('BG', 'Bulgaria', 'Europe', 'Bulgaria.svg'),
  ('BF', 'Burkina Faso', 'Africa', 'Burkina Faso.svg'),
  ('BI', 'Burundi', 'Africa', 'Burundi.svg'),
  ('KH', 'Cambodia', 'Asia', 'Cambodia.svg'),
  ('CM', 'Cameroon', 'Africa', 'Cameroon.svg'),
  ('CA', 'Canada', 'North America', 'Canada.svg'),
  ('CV', 'Cape Verde', 'Africa', 'Cape Verde.svg'),
  ('CF', 'Central African Republic', 'Africa', 'Central African Republic.svg'),
  ('CL', 'Chile', 'South America', 'Chile.svg'),
  ('CN', 'China', 'Asia', 'China.svg'),
  ('CO', 'Colombia', 'South America', 'Colombia.svg'),
  ('KM', 'Comoros', 'Africa', 'Comoros.svg'),
  ('CR', 'Costa Rica', 'North America', 'Costa Rica.svg'),
  ('HR', 'Croatia', 'Europe', 'Croatia.svg'),
  ('CU', 'Cuba', 'North America', 'Cuba.svg'),
  ('CY', 'Cyprus', 'Europe', 'Cyprus.svg'),
  ('CZ', 'Czech Republic', 'Europe', 'Czech Republic.svg'),
  ('CD', 'Democratic Republic of the Congo', 'Africa', 'Democratic Republic of the Congo.svg'),
  ('DK', 'Denmark', 'Europe', 'Denmark.svg'),
  ('DJ', 'Djibouti', 'Africa', 'Djibouti.svg'),
  ('DM', 'Dominica', 'North America', 'Dominica.svg'),
  ('DO', 'Dominican Republic', 'North America', 'Dominican Republic.svg'),
  ('EG', 'Egypt', 'Africa', 'Egypt.svg'),
  ('SV', 'El Salvador', 'North America', 'El Salvador.svg'),
  ('GQ', 'Equatorial Guinea', 'Africa', 'Equatorial Guinea.svg'),
  ('ER', 'Eritrea', 'Africa', 'Eritrea.svg'),
  ('SZ', 'Eswatini', 'Africa', 'Eswatini.svg'),
  ('ET', 'Ethiopia', 'Africa', 'Ethiopia.svg'),
  ('FJ', 'Fiji', 'Oceania', 'Fiji.svg'),
  ('FI', 'Finland', 'Europe', 'Finland.svg'),
  ('FR', 'France', 'Europe', 'France.svg'),
  ('GA', 'Gabon', 'Africa', 'Gabon.svg'),
  ('GM', 'Gambia', 'Africa', 'Gambia.svg'),
  ('GE', 'Georgia', 'Asia', 'Georgia.svg'),
  ('DE', 'Germany', 'Europe', 'Germany.svg'),
  ('GH', 'Ghana', 'Africa', 'Ghana.svg'),
  ('GR', 'Greece', 'Europe', 'Greece.svg'),
  ('GD', 'Grenada', 'North America', 'Grenada.svg'),
  ('GT', 'Guatemala', 'North America', 'Guatemala.svg'),
  ('GN', 'Guinea', 'Africa', 'Guinea.svg'),
  ('GW', 'Guinea-Bissau', 'Africa', 'Guinea-Bissau.svg'),
  ('GY', 'Guyana', 'South America', 'Guyana.svg'),
  ('HT', 'Haiti', 'North America', 'Haiti.svg'),
  ('HN', 'Honduras', 'North America', 'Honduras.svg'),
  ('HU', 'Hungary', 'Europe', 'Hungary.svg'),
  ('IS', 'Iceland', 'Europe', 'Iceland.svg'),
  ('IN', 'India', 'Asia', 'India.svg'),
  ('ID', 'Indonesia', 'Asia', 'Indonesia.svg'),
  ('IR', 'Iran', 'Asia', 'Iran.svg'),
  ('IQ', 'Iraq', 'Asia', 'Iraq.svg'),
  ('IE', 'Ireland', 'Europe', 'Ireland.svg'),
  ('IT', 'Italy', 'Europe', 'Italy.svg'),
  ('CI', 'Ivory Coast', 'Africa', 'Ivory Coast.svg'),
  ('JM', 'Jamaica', 'North America', 'Jamaica.svg'),
  ('JP', 'Japan', 'Asia', 'Japan.svg'),
  ('JO', 'Jordan', 'Asia', 'Jordan.svg'),
  ('KZ', 'Kazakhstan', 'Asia', 'Kazakhstan.svg'),
  ('KE', 'Kenya', 'Africa', 'Kenya.svg'),
  ('KI', 'Kiribati', 'Oceania', 'Kiribati.svg'),
  ('KW', 'Kuwait', 'Asia', 'Kuwait.svg'),
  ('KG', 'Kyrgyzstan', 'Asia', 'Kyrgyzstan.svg'),
  ('LA', 'Laos', 'Asia', 'Laos.svg'),
  ('LV', 'Latvia', 'Europe', 'Latvia.svg'),
  ('LB', 'Lebanon', 'Asia', 'Lebanon.svg'),
  ('LS', 'Lesotho', 'Africa', 'Lesotho.svg'),
  ('LR', 'Liberia', 'Africa', 'Liberia.svg'),
  ('LY', 'Libya', 'Africa', 'Libya.svg'),
  ('LI', 'Liechtenstein', 'Europe', 'Liechtenstein.svg'),
  ('LT', 'Lithuania', 'Europe', 'Lithuania.svg'),
  ('LU', 'Luxembourg', 'Europe', 'Luxembourg.svg'),
  ('MG', 'Madagascar', 'Africa', 'Madagascar.svg'),
  ('MW', 'Malawi', 'Africa', 'Malawi.svg'),
  ('MY', 'Malaysia', 'Asia', 'Malaysia.svg'),
  ('MV', 'Maldives', 'Asia', 'Maldives.svg'),
  ('ML', 'Mali', 'Africa', 'Mali.svg'),
  ('MT', 'Malta', 'Europe', 'Malta.svg'),
  ('MH', 'Marshall Islands', 'Oceania', 'Marshall Islands.svg'),
  ('MR', 'Mauritania', 'Africa', 'Mauritania.svg'),
  ('MU', 'Mauritius', 'Africa', 'Mauritius.svg'),
  ('MX', 'Mexico', 'North America', 'Mexico.svg'),
  ('FM', 'Micronesia', 'Oceania', 'Micronesia.svg'),
  ('MD', 'Moldova', 'Europe', 'Moldova.svg'),
  ('MC', 'Monaco', 'Europe', 'Monaco.svg'),
  ('MN', 'Mongolia', 'Asia', 'Mongolia.svg'),
  ('ME', 'Montenegro', 'Europe', 'Montenegro.svg'),
  ('MA', 'Morocco', 'Africa', 'Morocco.svg'),
  ('MZ', 'Mozambique', 'Africa', 'Mozambique.svg'),
  ('NA', 'Namibia', 'Africa', 'Namibia.svg'),
  ('NR', 'Nauru', 'Oceania', 'Nauru.svg'),
  ('NP', 'Nepal', 'Asia', 'Nepal.svg'),
  ('NL', 'Netherlands', 'Europe', 'Netherlands.svg'),
  ('NZ', 'New Zealand', 'Oceania', 'New Zealand.svg'),
  ('NI', 'Nicaragua', 'North America', 'Nicaragua.svg'),
  ('NE', 'Niger', 'Africa', 'Niger.svg'),
  ('NG', 'Nigeria', 'Africa', 'Nigeria.svg'),
  ('KP', 'North Korea', 'Asia', 'North Korea.svg'),
  ('MK', 'North Macedonia', 'Europe', 'North Macedonia.svg'),
  ('NO', 'Norway', 'Europe', 'Norway.svg'),
  ('OM', 'Oman', 'Asia', 'Oman.svg'),
  ('PK', 'Pakistan', 'Asia', 'Pakistan.svg'),
  ('PW', 'Palau', 'Oceania', 'Palau.svg'),
  ('PG', 'Papua New Guinea', 'Oceania', 'Papua New Guinea.svg'),
  ('PY', 'Paraguay', 'South America', 'Paraguay.svg'),
  ('PE', 'Peru', 'South America', 'Peru.svg'),
  ('PH', 'Philippines', 'Asia', 'Philippines.svg'),
  ('PL', 'Poland', 'Europe', 'Poland.svg'),
  ('PT', 'Portugal', 'Europe', 'Portugal.svg'),
  ('QA', 'Qatar', 'Asia', 'Qatar.svg'),
  ('CG', 'Republic of the Congo', 'Africa', 'Republic of the Congo.svg'),
  ('RO', 'Romania', 'Europe', 'Romania.svg'),
  ('RU', 'Russia', 'Europe', 'Russia.svg'),
  ('RW', 'Rwanda', 'Africa', 'Rwanda.svg'),
  ('KN', 'Saint Kitts and Nevis', 'North America', 'Saint Kitts and Nevis.svg'),
  ('LC', 'Saint Lucia', 'North America', 'Saint Lucia.svg'),
  ('VC', 'Saint Vincent and the Grenadines', 'North America', 'Saint Vincent and the Grenadines.svg'),
  ('WS', 'Samoa', 'Oceania', 'Samoa.svg'),
  ('SM', 'San Marino', 'Europe', 'San Marino.svg'),
  ('ST', 'Sao Tome and Principe', 'Africa', 'Sao Tome and Principe.svg'),
  ('SA', 'Saudi Arabia', 'Asia', 'Saudi Arabia.svg'),
  ('SN', 'Senegal', 'Africa', 'Senegal.svg'),
  ('RS', 'Serbia', 'Europe', 'Serbia.svg'),
  ('SC', 'Seychelles', 'Africa', 'Seychelles.svg'),
  ('SL', 'Sierra Leone', 'Africa', 'Sierra Leone.svg'),
  ('SG', 'Singapore', 'Asia', 'Singapore.svg'),
  ('SK', 'Slovakia', 'Europe', 'Slovakia.svg'),
  ('SI', 'Slovenia', 'Europe', 'Slovenia.svg'),
  ('SB', 'Solomon Islands', 'Oceania', 'Solomon Islands.svg'),
  ('SO', 'Somalia', 'Africa', 'Somalia.svg'),
  ('ZA', 'South Africa', 'Africa', 'South Africa.svg'),
  ('KR', 'South Korea', 'Asia', 'South Korea.svg'),
  ('SS', 'South Sudan', 'Africa', 'South Sudan.svg'),
  ('ES', 'Spain', 'Europe', 'Spain.svg'),
  ('LK', 'Sri Lanka', 'Asia', 'Sri Lanka.svg'),
  ('SD', 'Sudan', 'Africa', 'Sudan.svg'),
  ('SR', 'Suriname', 'South America', 'Suriname.svg'),
  ('SE', 'Sweden', 'Europe', 'Sweden.svg'),
  ('CH', 'Switzerland', 'Europe', 'Switzerland.svg'),
  ('SY', 'Syria', 'Asia', 'Syria.svg'),
  ('TJ', 'Tajikistan', 'Asia', 'Tajikistan.svg'),
  ('TZ', 'Tanzania', 'Africa', 'Tanzania.svg'),
  ('TH', 'Thailand', 'Asia', 'Thailand.svg'),
  ('TL', 'Timor-Leste', 'Asia', 'Timor-Leste.svg'),
  ('TG', 'Togo', 'Africa', 'Togo.svg'),
  ('TO', 'Tonga', 'Oceania', 'Tonga.svg'),
  ('TT', 'Trinidad and Tobago', 'North America', 'Trinidad and Tobago.svg'),
  ('TN', 'Tunisia', 'Africa', 'Tunisia.svg'),
  ('TR', 'Turkey', 'Asia', 'Turkey.svg'),
  ('TM', 'Turkmenistan', 'Asia', 'Turkmenistan.svg'),
  ('TV', 'Tuvalu', 'Oceania', 'Tuvalu.svg'),
  ('UG', 'Uganda', 'Africa', 'Uganda.svg'),
  ('UA', 'Ukraine', 'Europe', 'Ukraine.svg'),
  ('AE', 'United Arab Emirates', 'Asia', 'United Arab Emirates.svg'),
  ('GB', 'United Kingdom', 'Europe', 'United Kingdom.svg'),
  ('US', 'United States', 'North America', 'United States.svg'),
  ('UY', 'Uruguay', 'South America', 'Uruguay.svg'),
  ('UZ', 'Uzbekistan', 'Asia', 'Uzbekistan.svg'),
  ('VU', 'Vanuatu', 'Oceania', 'Vanuatu.svg'),
  ('VA', 'Vatican City', 'Europe', 'Vatican City.svg'),
  ('VE', 'Venezuela', 'South America', 'Venezuela.svg'),
  ('VN', 'Vietnam', 'Asia', 'Vietnam.svg'),
  ('YE', 'Yemen', 'Asia', 'Yemen.svg'),
  ('ZM', 'Zambia', 'Africa', 'Zambia.svg'),
  ('ZW', 'Zimbabwe', 'Africa', 'Zimbabwe.svg')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  continent = VALUES(continent),
  flag = VALUES(flag);
